# Generated by Django 3.2.21 on 2023-09-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='../default_profile_igf8vw', upload_to='profile_images/'),
        ),
    ]
