# Generated by Django 3.2.21 on 2023-09-21 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('CHORUS', 'Chorus'), ('LOOPER', 'Looper'), ('OCTAVE', 'Octave'), ('FUZZ', 'Fuzz'), ('OVERDRIVE AND DISTORTION', 'Overdrive and Distortion'), ('COMPRESSOR', 'Compressor')], default='£', max_length=50)),
                ('price', models.CharField(choices=[('£', '£'), ('££', '££'), ('£££', '£££'), ('££££', '££££'), ('£££££', '£££££')], default='£', max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedals.brands')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
