# Generated by Django 3.2.21 on 2023-09-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedals', '0002_pedal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedal',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedals.brands'),
        ),
    ]
