# Generated by Django 3.2.21 on 2023-09-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedals', '0004_auto_20230923_1621'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pedal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='pedals.pedal'),
        ),
    ]
